### ISSUE TITLE
Create index.js

### ISSUE THREAD

**Issue by srgraham** [fracz/coffeelint-forbidden-regex#4]
In order for this coffeelint rule to be included properly as a dependency, it needs to have an index.js to automatically run. In order to avoid forcing the user to `coffee --compile` the index.coffee, it would be convenient to either include the compiled index.coffee as an index.js or to rename index.coffee to something like forbidden_regex.coffee and having an index.js that looks like this:

```
require('coffee-script/register');
module.exports = require('./forbidden_regex');
```

That's at least how I've seen it done.

**Comment by fracz** [comment]
I have created [index.js](https://github.com/fracz/coffeelint-forbidden-regex/blob/master/index.js) file that references the rule. I have copypasted it from [coffeelint-camel-case-vars](https://github.com/bsklaroff/coffeelint-camel-case-vars/blob/master/index.js).

Does it solve your issue?

**Comment by srgraham** [comment]
Yes, however it might also be beneficial to rename the index.coffee to something else. That way no one will accidentally compile it and overwrite the special index.js. But either way, your edit solves my issue. Thanks!

**Comment by fracz** [comment]
[0.1.1](https://github.com/fracz/coffeelint-forbidden-regex/releases/tag/0.1.1) contains it.
